// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/account/v1alpha1/device.proto

package account

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DeviceData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DeviceData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeviceData with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeviceDataMultiError, or
// nil if none found.
func (m *DeviceData) ValidateAll() error {
	return m.validate(true)
}

func (m *DeviceData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetCreateTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeviceDataValidationError{
					field:  "CreateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeviceDataValidationError{
					field:  "CreateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreateTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeviceDataValidationError{
				field:  "CreateTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdateTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeviceDataValidationError{
					field:  "UpdateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeviceDataValidationError{
					field:  "UpdateTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdateTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeviceDataValidationError{
				field:  "UpdateTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Device

	// no validation rules for Ip

	if len(errors) > 0 {
		return DeviceDataMultiError(errors)
	}

	return nil
}

// DeviceDataMultiError is an error wrapping multiple validation errors
// returned by DeviceData.ValidateAll() if the designated constraints aren't met.
type DeviceDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeviceDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeviceDataMultiError) AllErrors() []error { return m }

// DeviceDataValidationError is the validation error returned by
// DeviceData.Validate if the designated constraints aren't met.
type DeviceDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeviceDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeviceDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeviceDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeviceDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeviceDataValidationError) ErrorName() string { return "DeviceDataValidationError" }

// Error satisfies the builtin error interface
func (e DeviceDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeviceData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeviceDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeviceDataValidationError{}

// Validate checks the field values on GetDeviceRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetDeviceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDeviceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDeviceRequestMultiError, or nil if none found.
func (m *GetDeviceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDeviceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeviceId

	if len(errors) > 0 {
		return GetDeviceRequestMultiError(errors)
	}

	return nil
}

// GetDeviceRequestMultiError is an error wrapping multiple validation errors
// returned by GetDeviceRequest.ValidateAll() if the designated constraints
// aren't met.
type GetDeviceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDeviceRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDeviceRequestMultiError) AllErrors() []error { return m }

// GetDeviceRequestValidationError is the validation error returned by
// GetDeviceRequest.Validate if the designated constraints aren't met.
type GetDeviceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDeviceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDeviceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDeviceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDeviceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDeviceRequestValidationError) ErrorName() string { return "GetDeviceRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetDeviceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDeviceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDeviceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDeviceRequestValidationError{}

// Validate checks the field values on GetDevicesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDevicesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDevicesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDevicesResponseMultiError, or nil if none found.
func (m *GetDevicesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDevicesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetDevices() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetDevicesResponseValidationError{
						field:  fmt.Sprintf("Devices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetDevicesResponseValidationError{
						field:  fmt.Sprintf("Devices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetDevicesResponseValidationError{
					field:  fmt.Sprintf("Devices[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Message

	// no validation rules for DeviceId

	if len(errors) > 0 {
		return GetDevicesResponseMultiError(errors)
	}

	return nil
}

// GetDevicesResponseMultiError is an error wrapping multiple validation errors
// returned by GetDevicesResponse.ValidateAll() if the designated constraints
// aren't met.
type GetDevicesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDevicesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDevicesResponseMultiError) AllErrors() []error { return m }

// GetDevicesResponseValidationError is the validation error returned by
// GetDevicesResponse.Validate if the designated constraints aren't met.
type GetDevicesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDevicesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDevicesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDevicesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDevicesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDevicesResponseValidationError) ErrorName() string {
	return "GetDevicesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetDevicesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDevicesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDevicesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDevicesResponseValidationError{}

// Validate checks the field values on GetDeviceResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetDeviceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDeviceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDeviceResponseMultiError, or nil if none found.
func (m *GetDeviceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDeviceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDevice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDeviceResponseValidationError{
					field:  "Device",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDeviceResponseValidationError{
					field:  "Device",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDevice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDeviceResponseValidationError{
				field:  "Device",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDeviceResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDeviceResponseValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDeviceResponseValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Message

	if len(errors) > 0 {
		return GetDeviceResponseMultiError(errors)
	}

	return nil
}

// GetDeviceResponseMultiError is an error wrapping multiple validation errors
// returned by GetDeviceResponse.ValidateAll() if the designated constraints
// aren't met.
type GetDeviceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDeviceResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDeviceResponseMultiError) AllErrors() []error { return m }

// GetDeviceResponseValidationError is the validation error returned by
// GetDeviceResponse.Validate if the designated constraints aren't met.
type GetDeviceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDeviceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDeviceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDeviceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDeviceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDeviceResponseValidationError) ErrorName() string {
	return "GetDeviceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetDeviceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDeviceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDeviceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDeviceResponseValidationError{}

// Validate checks the field values on DeleteDeviceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteDeviceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDeviceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDeviceRequestMultiError, or nil if none found.
func (m *DeleteDeviceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDeviceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteDeviceRequestMultiError(errors)
	}

	return nil
}

// DeleteDeviceRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteDeviceRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteDeviceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDeviceRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDeviceRequestMultiError) AllErrors() []error { return m }

// DeleteDeviceRequestValidationError is the validation error returned by
// DeleteDeviceRequest.Validate if the designated constraints aren't met.
type DeleteDeviceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDeviceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDeviceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDeviceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDeviceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDeviceRequestValidationError) ErrorName() string {
	return "DeleteDeviceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDeviceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDeviceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDeviceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDeviceRequestValidationError{}

// Validate checks the field values on DeleteDeviceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteDeviceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDeviceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDeviceResponseMultiError, or nil if none found.
func (m *DeleteDeviceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDeviceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return DeleteDeviceResponseMultiError(errors)
	}

	return nil
}

// DeleteDeviceResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteDeviceResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteDeviceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDeviceResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDeviceResponseMultiError) AllErrors() []error { return m }

// DeleteDeviceResponseValidationError is the validation error returned by
// DeleteDeviceResponse.Validate if the designated constraints aren't met.
type DeleteDeviceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDeviceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDeviceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDeviceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDeviceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDeviceResponseValidationError) ErrorName() string {
	return "DeleteDeviceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDeviceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDeviceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDeviceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDeviceResponseValidationError{}
